[manifest]
version = "0.0.1"
dump_lua = true
priority = 9999

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''(.*)tab_definition_function(.*)=(.*)G.UIDEF.used_vouchers,(.*)
(.*)},(.*)'''
position = "after"
payload = '''
{
    label = localize('b_unik_banished_items'),
    tab_definition_function = G.UIDEF.unik_banished_items,
},
'''
match_indent = true