[manifest]
version = "0.0.1"
dump_lua = true
priority = 99

[[patches]]
[patches.pattern]
target = '''=[SMODS Blindside "lib/utils/declarations.lua"]'''
pattern = '''"tag_bld_hiss",'''
match_indent = true
position = 'after'
payload = '''
'tag_unik_blindside_dethroning',
'm_unik_blindside_halved',
'm_unik_blindside_prince',
'm_unik_blindside_catterfly',
'm_unik_blindside_blossom',
'm_unik_blindside_descending',
'''