[manifest]
version = "0.0.1"
dump_lua = true
priority = -1

##Another buffoonery fix, without talisman, buff likes to do this, causing very buffed values for emult/echips. This fixes this.
[[patches]]
[patches.pattern]
target = '''=[SMODS Buffoonery "Buffoonery.lua"]'''
pattern = '''NFS.load(Buffoonery.path .. 'notalisman.lua')()'''
position = "before"
payload = '''
if not Cryptid then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Buffoonery "Buffoonery.lua"]'''
pattern = '''NFS.load(Buffoonery.path .. 'notalisman.lua')()'''
position = "after"
payload = '''
end
'''
match_indent = true