[manifest]
version = "0.0.1"
dump_lua = true
priority = 9999

###i had to
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''delay(0.3)
if not (SMODS.Mods["Talisman"] or {}).can_load then
    evaluate_play_after(text, disp_text, poker_hands, scoring_hand, non_loc_disp_text, percent, percent_delta)
end
return text, disp_text, poker_hands, scoring_hand, non_loc_disp_text, percent, percent_delta
end
function evaluate_play_after(text, disp_text, poker_hands, scoring_hand, non_loc_disp_text, percent, percent_delta)'''
position = "at"
payload = '''
--deleted
delay(0.3)
if not UNIK.has_talisman() then
    evaluate_play_after(text, disp_text, poker_hands, scoring_hand, non_loc_disp_text, percent, percent_delta)
end
return text, disp_text, poker_hands, scoring_hand, non_loc_disp_text, percent, percent_delta
end
function evaluate_play_after(text, disp_text, poker_hands, scoring_hand, non_loc_disp_text, percent, percent_delta)
--deleted
'''
match_indent = true