[manifest]
version = "0.0.1"
dump_lua = true
priority = 214748365
### video poker functions:
### force playing all cards in hand

### Always have infinite selection limit in video poker to avoid softlocking.
[[patches]]
[patches.regex]
target = "cardarea.lua"
pattern = "(.*)#self.highlighted(.*)self.config.highlighted_limit."
position = "after"
payload = "   and not G.GAME.unik_video_poker_rules   "
match_indent = true